### ISSUE TITLE
与 obfsproxy 使用的疑问

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1028]
用了 obfsproxy 混淆 ss 的数据是否就和开启了 OTA 功能的 ss 安全性相媲美了呢？

**Comment by suikatomoki** [comment]
ota主要作用于数据包完整性校验，obfsproxy是用来混淆数据的，不能拿在一起进行比较。目前还没有因为ss的协议不够安全而导致大规模封服务器的情况，不用太在意。

**Comment by Sherlock-Holo** [comment]
但是ss现在的协议可能不太够用了，咱的不用混淆基本用不了

suika <notifications@github.com>于2017年1月2日周一 02:10写道：

**Comment by debiansid** [comment]
不用混淆跑得一样啊 电信

**Comment by Sherlock-Holo** [comment]
咱的不用根本上不去

debiansid <notifications@github.com>于2017年1月2日周一 11:35写道：

**Comment by madeye** [comment]
Nope, obfs won't improve the security. If you don't have any QoS issue, just don't enable it.

**Comment by Sherlock-Holo** [comment]
但是咱的开了obfs后就可以直连，不开根本不能使用，觉得开了后还是解决了一下特征问题的

Max Lv <notifications@github.com>于2017年1月2日周一 11:42写道：

**Comment by cokebar** [comment]
@madeye May be it is not only useful when having QoS issue. In my company's local network, the firewall seems to have a strategy that blocking all the unkown protocals. It has no problem to use an HTTP(S) proxy but when using shadowsocks, the tracfic will be blocked after an uncertain time period (sometime it won't be blocked, but sometime it is blocked in 1~5min) . And there's the error log at the client side:
`[2017-01-02 15:31:01] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 从传输流收到意外的 EOF 或 0 个字节。
   在 System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-01-02 15:32:01] Shadowsocks started
[2017-01-02 15:33:59] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2017-01-02 15:33:59] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)`

Now I'm testing the obfs function. Maybe it is useful for this situation because the firewall may recognise it as a HTTP(S) connection and won't block it. @Sherlock-Holo Maybe you are encounter the similar issue?
