### ISSUE TITLE
3.0.3 build failed - 

### ISSUE THREAD

**Issue by tedaz** [shadowsocks/shadowsocks-libev#1328]
### What version of shadowsocks-libev are you using?
Shadowsocks-libev 3.0.3 OpenWRT version.

### What operating system are you using?
Ubuntu 16.04

### What did you do?
Build shadowsocks-libev.

### What did you see instead?
configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.
make[2]: *** [/lede/build_dir/target-x86_64_musl/shadowsocks-libev//shadowsocks-libev-3.0.3-1/.configured_378b7d77286ceb1b05fea273476f3a6c] Error 1

### What is your config in detail (with all sensitive info masked)?
Already installed libudns-dev, but Ubuntu does not have the package udns-devel.
With the same Ubuntu system and same software packages, build 3.0.1 successfully.
It seems that the 3.0.3 have some issues.

**Comment by vfreex** [comment]
Of cause installing `libudns-dev` on your build host is useless, because you are cross-compiling for another platform, not your host.
As far as I know, LEDE project do not have udns in their official package repository. IMO you should download the source code of udns and perform a static linking to it.

**Comment by simonsmh** [comment]
https://github.com/shadowsocks/openwrt-feeds/blob/master/base/libudns/Makefile

**Comment by tianlichunhong** [comment]
Could you tell me the detail, how to use this link:https://github.com/shadowsocks/openwrt-feeds/blob/master/base/libudns/Makefile, thank you!
