### ISSUE TITLE
contos yum -y update更新后,出现下面的问题,怎么办

### ISSUE THREAD

**Issue by ooogooo** [shadowsocks/shadowsocks-libev#1499]
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-05-13 05:03:07 UTC; 22s ago
     Docs: man:shadowsocks-libev(8)
  Process: 2860 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=216/GROUP)
 Main PID: 2860 (code=exited, status=216/GROUP)

May 13 05:03:07 o systemd[1]: Started Shadowsocks-libev Default Server Service.
May 13 05:03:07 o systemd[1]: Starting Shadowsocks-libev Default Server Service...
May 13 05:03:07 osystemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=216/GROUP
May 13 05:03:07 o systemd[1]: Unit shadowsocks-libev.service entered failed state.
May 13 05:03:07 o systemd[1]: shadowsocks-libev.service failed.

用ss测试是
ss-server -c /etc/shadowsocks-libev/config.json
ss-server: error while loading shared libraries: libsodium.so.13: cannot open shared object file: No such file or directory

这个问题怎么搞定.

**Comment by ShinoharaYuri** [comment]
ss-server: error while loading shared libraries: libsodium.so.13: cannot open shared object file: No such file or directory

libsodium.so

**Comment by blambin** [comment]
我今天 更新 了,用systemd运行 也是报这个错,但是手动运行命令可以正常运行 

[blambin@blabla system]$  sudo systemctl status shadowsocks-libev.service
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-05-13 17:04:37 UTC; 3s ago
     Docs: man:shadowsocks-libev(8)
  Process: 2494 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=216/GROUP)
 Main PID: 2494 (code=exited, status=216/GROUP)

May 13 17:04:37 blabla systemd[1]: Started Shadowsocks-libev Default Server Service.
May 13 17:04:37 blabla systemd[1]: Starting Shadowsocks-libev Default Server Service...
May 13 17:04:37 blabla systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=216/GROUP
May 13 17:04:37 blabla systemd[1]: Unit shadowsocks-libev.service entered failed state.
May 13 17:04:37 blabla systemd[1]: shadowsocks-libev.service failed.

[blambin@blabla system]$ sudo /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json
 2017-05-13 17:06:01 INFO: initializing ciphers... chacha20
 2017-05-13 17:06:01 INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbers
Installing the rng-utils/rng-tools or haveged packages may help.
On virtualized Linux environments, also consider using virtio-rng.
The service will not start until enough entropy has been collected.
 2017-05-13 17:06:01 INFO: tcp server listening at xxxx:xxx
 2017-05-13 17:06:01 INFO: running from root user

**Comment by rogers0** [comment]
I don't use centos for years, so comments below are just for reference.

@ooogooo @ShinoharaYuri I guess your ss-libev was built with libraries in /usr/local/lib, so it built OK, but it cannot find the libraries when starting.

@blambin you need to generate more entropy before starting ss-libev. I recommend to install haveged.
You can also check #1384

**Comment by ooogooo** [comment]
在另一个答案里面看到了,搞定了,就是把配置用户组的前面加一个#注释掉就可以了

是用户组的问题

**Comment by whao** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/719
