### ISSUE TITLE
使用ss libev+simple obfs的时候，如果节点有域名，在http或者tls混淆的情况下，是否还需要填写混淆参数？

### ISSUE THREAD

**Issue by himan85** [shadowsocks/shadowsocks-libev#1628]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
ss-libev 3.0.8 + simple-obfs 0.0.3

### What operating system are you using?
debian 8 + nginx

**Comment by Windendless** [comment]
要

**Comment by rogers0** [comment]
@himan85 @Windendless I have added a sample config for simple-obfs since version 0.0.3-4
It already reached jessie-backports-sloppy and stretch-backports, in Debian official repository.
You can see the default setting in:
 - https://anonscm.debian.org/cgit/collab-maint/simple-obfs.git/tree/debian/config.json
and it will be installed to your system in:
 - /etc/shadowsocks-libev/config-obfs.json

Please let me know if it's ok, or anything can be improved.
Thank you!

**Comment by Windendless** [comment]
@rogers0 I think it's ok
