### ISSUE TITLE
Build shadowsocks-libev v3.0.8 with cygwin on Windows

### ISSUE THREAD

**Issue by cuteribs** [shadowsocks/shadowsocks-libev#1665]
> Same people may be interested.

### Reqired packages:
`gcc-core, automake, autoconf, libtool, libev-devel, libsodium-devel, mbedtls-devel, libpcre-devel`

### Compile process
```shell
$ git clone git://github.com/shadowsocks/libudns
$ cd libudns
$ ./autogen.sh
$ ./configure
$ make
$ cp .libs/libudns.a /lib/


$ git clone -b v3.0.8 git://github.com/shadowsocks/shadowsocks-libev
$ cd shadowsocks-libev
$ git submodule init
$ git submodule update
$ ./autogen.sh
$ ./configure --disable-documentation
$ make

```

**Comment by AnyoeDove** [comment]
@cuteribs 
hi, when i tried to compile libudns, and it output like this:

> make[1]: 进入目录“/home/Anyoe/libudns”
  CC       udns_dn.lo
  CC       udns_dntosp.lo
  CC       udns_parse.lo
  CC       udns_resolver.lo
  CC       udns_init.lo
  CC       udns_misc.lo
  CC       udns_XtoX.lo
  CC       udns_rr_a.lo
  CC       udns_rr_ptr.lo
  CC       udns_rr_mx.lo
  CC       udns_rr_txt.lo
  CC       udns_bl.lo
  CC       udns_rr_srv.lo
  CC       udns_rr_naptr.lo
  CC       udns_codes.lo
  CC       udns_jran.lo
  CCLD     libudns.la
 libtool: warning: undefined symbols not allowed in x86_64-unknown-cygwin shared libraries; building static only
make[1]: 离开目录“/home/Anyoe/libudns”

and i dont know how to fix libudns, so i just cp to /lib like u said. when i tried to compile shadowsocks-libev ./configure output these

> checking for udns.h... no
configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.

so i know libudns its not working. how to compile it right?

btw i installed all required packages

**Comment by dreamtrail** [comment]
You need also copy udns.h to /usr/include/

**Comment by cuteribs** [comment]
@dreamtrail @AnyoeDove Maybe I forgot to list "make install", I don't recall moving any .h files.

**Comment by smallb** [comment]
configure:16131: checking for dns_dnlen in -ludns
configure:16156: gcc -o conftest.exe -g -O2 -mno-ms-bitfields -pthread -fstack-protector   conftest.c -ludns   -lsodium -lmbedcrypto -lpcre  >&5
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /lib/../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /lib/../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /lib/../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/../lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: skipping incompatible /usr/lib/libudns.a when searching for -ludns
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -ludns
collect2: error: ld returned 1 exit status
configure:16156: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "shadowsocks-libev"
| #define PACKAGE_TARNAME "shadowsocks-libev"
| #define PACKAGE_VERSION "3.0.8"
| #define PACKAGE_STRING "shadowsocks-libev 3.0.8"
| #define PACKAGE_BUGREPORT "max.c.lv@gmail.com"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define PACKAGE "shadowsocks-libev"
| #define VERSION "3.0.8"
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_PCRE_H 1
| #define HAVE_LIBPCRE 1
| #define TLS __thread
| #define restrict __restrict
| #define HAVE_NETDB_H 1
| #define HAVE_DECL_INET_NTOP 1
| #define HAVE_LIMITS_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_ARPA_INET_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_LANGINFO_H 1
| #define HAVE_LOCALE_H 1
| #define HAVE_NETDB_H 1
| #define HAVE_NETINET_IN_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_SYS_IOCTL_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_NET_IF_H 1
| #define CONNECT_IN_PROGRESS EINPROGRESS
| #define STDC_HEADERS 1
| #define HAVE_SYS_WAIT_H 1
| #define TIME_WITH_SYS_TIME 1
| #define HAVE_FORK 1
| #define HAVE_VFORK 1
| #define HAVE_WORKING_VFORK 1
| #define HAVE_WORKING_FORK 1
| #define HAVE_SYS_SELECT_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define SELECT_TYPE_ARG1 int
| #define SELECT_TYPE_ARG234 (fd_set *)
| #define SELECT_TYPE_ARG5 (struct timeval *)
| #define RETSIGTYPE void
| #define HAVE_MEMSET 1
| #define HAVE_SELECT 1
| #define HAVE_SETREUID 1
| #define HAVE_STRERROR 1
| #define HAVE_GET_CURRENT_DIR_NAME 1
| #define HAVE_GETPWNAM_R 1
| #define HAVE_SETRLIMIT 1
| #define HAVE_MALLOC 1
| #define HAVE_MEMSET 1
| #define HAVE_POSIX_MEMALIGN 1
| #define HAVE_SOCKET 1
| #define HAVE_IPv6 1
| #define HAVE_UDNS_H 1
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char dns_dnlen ();
| int
| main ()
| {
| return dns_dnlen ();
|   ;
|   return 0;
| }
configure:16165: result: no
configure:16170: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.

libudns编译在lib里面了
udns.h头文件也在include里面了
但是还是报了这个错误....
3.1.1 版本

**Comment by twfcc** [comment]
I got some problem while compiling shadowsocks-libev under cygwin x86_64

massage link [https://pastebin.com/N0GenU03](url)

any ideas? Thanks a lot
