### ISSUE TITLE
scripts脚本build_deb.sh疑问

### ISSUE THREAD

**Issue by liangenbo** [shadowsocks/shadowsocks-libev#1691]
请问ubuntu系统采用scripts下面的build_deb.sh中会去下载 https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git  这个地方的源码来编译而不是采用 该github（https://github.com/shadowsocks/shadowsocks-libev.git）的代码路径呢？

**Comment by hosiet** [comment]
Yes, it will use the source code on anonscm.debian.org instead of github.com.

**Comment by liangenbo** [comment]
OK，Ths，为什么会有这种考虑呢？目前是发现github上的代码已经到3.1.0了，而anonscm.debian.org的源码还在3.0.8上，因此发现不同步。

**Comment by hosiet** [comment]
Code on GitHub is uncontrollable. Fetching git HEAD is dangerous, since any buggy commit would immediately results in build failure. New tags (releases) need to be reviewed so that the build script can handle it properly. For example, the new version (3.1.0) replaced libudns with c-ares, which requires various changes in `build_deb.sh` script. Before the migration finishes, fetching the old version from anonscm.debian.org is the most appropriate choice.

You might think that we could use explicit tag from GitHub (e.g., tag 3.0.8 when 3.1.0 is not ready). That is not really the optimal approach. We need some official packaging instructions from Debian, which is hosted on anonscm.debian.org. (The `debian/` dir on github repository is not *that* official since it needs to retain certain level of compatibility with older Debian/Ubuntu systems). Meanwhile, code from old tag **cannot be altered anymore**, which is a big problem.

I hope that explains the reason why we are using code from anonscm.debian.org.

**Comment by liangenbo** [comment]
明白了，谢谢。

**Comment by rogers0** [comment]
@liangenbo 3.1.0 now is in experimental repo, so maybe you can help to test
- https://packages.debian.org/experimental/shadowsocks-libev

**Comment by liangenbo** [comment]
@rogers0   OK, thank you. I have compiled and installed it。

**Comment by myliyifei** [comment]
编译脚本不能指定tag的参数  ppa仓库又下不到老版本的deb啊

**Comment by myliyifei** [comment]
@hosiet 现在git上面已经是3.1.0+的代码了，我用checkout v3.0.8,  编译一个是有点问题，另外一个就是我看最终的编译版本还是3.1.1，怎么样编译回老版本

**Comment by hosiet** [comment]
I'm not sure what your need is. `build_deb.sh` would always point to latest supported version in Debian, say v3.1.1 at the moment. If you encounter bugs in it, please report it so that bugs could get fixed in next upstream release.

I believe build_deb.sh shouldn't provide built-in support to build random specified version in history. If you do want a certain old one, you can always hack into the script and checkout that tag from git repository.

**Comment by hosiet** [comment]
Please always keep in mind about the splitted status between git repo **here** and those **on anonscm.debian.org**. Checking out an **old version of *build_deb.sh** is not useful at all since the repository it looks at would always be those on anonscm.debian.org, with latest code on master branch.

A proper solution is to modify `build_deb.sh` by yourself so that the script no longer checkout master branch. You will need to manually specify the git tag you need for building inside the script.
