### ISSUE TITLE
[Question] Redirect Incoming Requests to local port

### ISSUE THREAD

**Issue by kooroshh** [shadowsocks/shadowsocks-libev#1766]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.3 with mbed TLS 2.4.0

### What operating system are you using?
Debian 8

### What did you expect to see?
redirect incoming requests to local port 

### What did you see instead?
connecting to remote server directly 

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"127.0.0.1",
    "server_port":4444,
    "password":"4444",
    "timeout":60,
    "method": "rc4-md5"
}
```
is there anyway to redirect incoming traffic to local port ?!

**Comment by terrytw** [comment]
If you want to redirect incoming traffic to local port 4444 to local port 5555, use this iptables rule:
iptables -t nat -A PREROUTING -p tcp --dport 4444 -j REDIRECT --to-ports 5555

**Comment by kooroshh** [comment]
it just redirect encrypted traffic i want to redirect decrypted traffic to local port (like squid) to add radius support

**Comment by terrytw** [comment]
I cannot understand what you are trying to say here, hence I can't help.

**Comment by kooroshh** [comment]
there is a feature in Stunnel or Zebedee that you can redirect incoming requests to other application , for example you can listen on port 9000 and redirect incoming requests to squid , then squid will handle the Authentication and Caching , as far as i know , Shadowsocks sends incoming requests directly to target host , i want to redirect them to my Caching / Auth Server . 
is this clear ? 
sorry for my bad english ^^

**Comment by terrytw** [comment]
I think you mean outgoing traffic? 

> "Incoming" and "outgoing" are from the perspective of the machine in question.
> 
> "Incoming" refers to packets which originate elsewhere and arrive at the machine, while "outgoing" refers to packets which originate at the machine and arrive elsewhere.

I presume what you mean is that the machine in question is a shadowsocks client, and what usually happens on a shadowsocks client (ss-local) is that it listens at a local port (e.g. 12345), and encrypt any data sent to that port and send it to target shadowsocks server. 

Or in the case of ss-redir, through the following rules:
iptables -t nat -N SHADOWSOCKS
iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 12345
All TCP traffic is redirected to port 12345, and shadowsocks client listens at local port 12345, and encrypt any data sent to that port and send it to target shadowsocks server.

So instead of sending it to the shadowsocks server, you want the data from shadowsocks client to be sent to another local port first, is that right?

In that case, make sure you are using ss-local or ss-redir, not the default shadowsocks-libev service, since default service runs ss-server. 

Your config looks right to me.

If you run `ss-local -c config .json` it should lead your outgoing traffic to local port 4444.

**Comment by kooroshh** [comment]
thanks for your reply ,
actually i'm looking for proxy cascading feature in shadowsocks ,  listen for socks5 requests forward it to https proxy that's all i want xD

**Comment by terrytw** [comment]
I get what you mean. 

```
{
    "server":"127.0.0.1",
    "server_port":4444,
    "local_port":3333
    "password":"4444",
    "timeout":60,
    "method": "rc4-md5"
}
```
and run `ss-local -c config .json`
Your https proxy should listen on 4444, while shadowsocks listens to socks5 request on 3333.
