### ISSUE TITLE
Measure data usage at IP level

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-libev#1998]
https://source.android.com/devices/tech/datausage/iface-overview:

> Mobile operators typically measure data usage at the Internet layer (IP).

I wonder if it's possible to change our implementation to measure rx/tx at IP level.

**Comment by madeye** [comment]
If so, packets from other Apps would be counted as well? For example, bypassed apps and apps in other work profiles.

**Comment by Mygod** [comment]
Actually maybe we should care about how vps provider measures data usage?

**Comment by madeye** [comment]
@Mygod Yes, actually different ISPs are using different measuring approaches as well.

Considering a maximum 64 bytes header (IP + TCP) and average 1000 bytes packets, at most 6.4% difference would be observed. However, if we consider the packet drop and NAT overhead, the difference should be even larger.

IMO, our current measuring is more accurate, ISPs should measure the payload sizes instead of packet sizes.

**Comment by Mygod** [comment]
Makes sense but ignoring packet drops etc. would require a stateful packet counter which might be a pretty big overhead.

**Comment by Mygod** [comment]
I guess it's impossible to do this considering plugins etc. It might be better implemented by the OS.
