### ISSUE TITLE
Unable to ping server when running shadowsocks-libev

### ISSUE THREAD

**Issue by Jayzisinstance** [shadowsocks/shadowsocks-libev#2005]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.1.3

### What operating system are you using?

CentOS 7 which running the ss-local

### What did you do?

If I run the Shadowsocks-libev software locally in KVM virtual machine, the server immediately unable to ping, then after I changed a machine on the same LAN, it was able to ping the server, but while i changed back to my vritual machine in KVM, it still unable to ping.

This is the `ping` command that is executed when I run shadowsocks-libev
```
[root@test ~]# ping x.x.x.x
PING x.x.x.x (x.x.x.x) 56(84) bytes of data.

--- x.x.x.x ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 2999ms
```

and `traceroute` result here

```
[root@test ~]# traceroute x.x.x.x
traceroute to x.x.x.x (x.x.x.x), 30 hops max, 60 byte packets
1 gateway (192.168.87.254) 0.602 ms 0.563 ms 0.705 ms
2 * * *
3 * * *
4 42.243.20.1 (42.243.20.1) 7.294 ms 7.457 ms 7.712 ms
5 106.57.243.149 (106.57.243.149) 6.689 ms 106.57.243.145 (106.57.243.145) 6.215 ms 106.57.243.149 (106.57.243.149) 6.872 ms
6 222.221.31.89 (222.221.31.89) 5.972 ms 2.893 ms 3.182 ms
7 202.97.76.181 (202.97.76.181) 28.675 ms 28.760 ms 28.739 ms
8 59.43.80.21 (59.43.80.21) 31.037 ms 29.213 ms 31.318 ms
9 59.43.130.110 (59.43.130.110) 59.100 ms 58.592 ms 56.481 ms
10 59.43.187.158 (59.43.187.158) 42.455 ms 59.43.187.126 (59.43.187.126) 42.060 ms 59.43.187.122 (59.43.187.122) 28.441 ms
11 59.43.187.182 (59.43.187.182) 40.844 ms 59.43.183.110 (59.43.183.110) 48.851 ms 59.43.188.126 (59.43.188.126) 45.716 ms
12 59.43.187.22 (59.43.187.22) 49.550 ms 59.43.181.190 (59.43.181.190) 47.862 ms 59.43.186.122 (59.43.186.122) 44.213 ms
13 118.184.22.78 (118.184.22.78) 45.940 ms 47.789 ms 46.682 ms
14 * * *
```

There is something should be noted is that the last IP address `118.184.22.78` is not my server IP, but there all is at the same LAN `118.184.0.0\16`

But while I stop the shadowsocks-libev and after waiting 1 mins, it will able to ping the server again.

This `traceroute` command executed after I waiting 1 mins and able to ping server.
```
[root@test ~]# traceroute x.x.x.x
traceroute to x.x.x.x (x.x.x.x), 30 hops max, 60 byte packets
 1  gateway (192.168.87.254)  0.365 ms  0.504 ms  0.483 ms
 2  * * *
 3  * * *
 4  42.243.20.1 (42.243.20.1)  8.187 ms  8.275 ms  8.246 ms
 5  106.57.243.149 (106.57.243.149)  4.029 ms 106.57.243.145 (106.57.243.145)  4.359 ms 106.57.243.149 (106.57.243.149)  3.976 ms
 6  222.221.31.89 (222.221.31.89)  4.112 ms 222.221.29.73 (222.221.29.73)  2.594 ms 222.221.31.89 (222.221.31.89)  3.189 ms
 7  202.97.76.181 (202.97.76.181)  28.482 ms  28.512 ms 202.97.76.21 (202.97.76.21)  32.630 ms
 8  59.43.80.21 (59.43.80.21)  29.371 ms  29.362 ms  31.111 ms
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

I think it's maybe a bug on the shadowsocks network connection or if it's not a bug, it's that gfw has acted or something else, so I think it's necessary for developers to feedback this information.

### What did you expect to see?

Noting

### What did you see instead?

Nothing

### What is your config in detail (with all sensitive info masked)?

ss-local -l 1080 -s x.x.x.x -p 8000 -m xchacha20-ietf-poly1305 -k nobody -u

**Comment by madeye** [comment]
> If I run the Shadowsocks-libev software locally in KVM virtual machine, the server immediately unable to ping, then after I changed a machine ***on the same LAN***, it was able to ping the server

From your description, I think there is nothing to do with shadowsocks.

**Comment by liu-lulin** [comment]
The SS is not working after the update today.

 ___Bandwagon OpenVZ VPS Debian9



~# systemctl status shadowsocks-libev.service                 ● shadowsocks-libev.service - Shadowsocks-libev Default Server Serv
ice
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-03-30 15:12:5
3 CST; 23min ago
     Docs: man:shadowsocks-libev(8)
  Process: 214 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS
(code=exited, status=237/KEYRING)
 Main PID: 214 (code=exited, status=237/KEYRING)

Mar 30 15:12:53 localhost systemd[1]: Started Shadowsocks-libev Default Server Service.
Mar 30 15:12:53 localhost systemd[214]: shadowsocks-l
ibev.service: Failed to change ownership of session keyring: Permission denied
Mar 30 15:12:53 localhost systemd[214]: shadowsocks-l
ibev.service: Failed to set up kernel keyring: Permission denied
Mar 30 15:12:53 localhost systemd[214]: shadowsocks-l
ibev.service: Failed at step KEYRING spawning /usr/bin/ss-server: Permission denied
Mar 30 15:12:53 localhost systemd[1]: shadowsocks-lib
ev.service: Main process exited, code=exited, status=237/KEYRING
Mar 30 15:12:53 localhost systemd[1]: shadowsocks-lib
ev.service: Failed with result 'exit-code'.

**Comment by Jayzisinstance** [comment]
@madeye Yes... I changed a vps server now which is in USA not in HK, it's works now...I think maybe my ip was identified by GFW now.. Thx for you answer~
