### ISSUE TITLE
libmbedcrypto.so.0 error again

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-libev#2015]
### What version of shadowsocks-libev are you using?
3.1.3 

### What operating system are you using?
lede 17.01.4

### What did you do?
opkg update <package>

libmbedtls  has updated to 2.7.2-1 (official source)
before is 2.7.0-2 (sourceforce source)

so it's run-error again.  
@aa65535

**Comment by manjuprajna** [comment]
@s7lx if you upgraded mbedtls you need to compile new shadowsocks-libev, because when compiling shadowsocks-libev, it needs mbedtls-devl and libsodium-devel.
pre-compiled binaries is based on mbedtls 2.7.0 I think.
by the way it's not a good idea to opkg update and install new software, you'd better compile new firmware based on new mbedtls
