### ISSUE TITLE
some content in file build_deb.sh now need update

### ISSUE THREAD

**Issue by kentooo** [shadowsocks/shadowsocks-libev#2084]
debian was closed https://anonscm.debian.org , so there has some wrong when I execute the build_deb.sh file

I think the follow content need to update

https://github.com/shadowsocks/shadowsocks-libev/blob/8fd83e2686d6655be4f6ee9ae8b25c8f9b4b862d/scripts/build_deb.sh#L227-L239

https://github.com/shadowsocks/shadowsocks-libev/blob/8fd83e2686d6655be4f6ee9ae8b25c8f9b4b862d/scripts/build_deb.sh#L268-L276

**Comment by madeye** [comment]
This file is written by Debian package maintainer. Let's wait for the downstream updates.

**Comment by moonwater** [comment]
yes, I have the same error:
-------------------------------------------------
gbp:warning: Pristine-tar branch "pristine-tar" not found
gbp:info: Creating /home/user/shadowsocks-libev_3.2.0.orig.tar.gz
gbp:error: Error creating shadowsocks-libev_3.2.0.orig.tar.gz: Pristine-tar couldn't checkout "shadowsocks-libev_3.2.0.orig.tar.gz": pristine-tar: no pristine-tar branch found, use "pristine-tar commit" first
HEAD is now at 8fd83e2 Use chacha20-ietf as a default cipher instead of rc4-md5 (#2080)
/home/user/build-area
dpkg: error: cannot access archive 'shadowsocks-libev_*.deb': No such file or directory
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Cloning into 'simple-obfs'...
fatal: repository 'https://anonscm.debian.org/git/collab-maint/simple-obfs.git/' not found
./build_deb.sh: 127: cd: can't cd to simple-obfs
Usage:
    mk-build-deps --help|--version
