### ISSUE TITLE
shadowsocks-libev-server@.service 需要等待 network-online.target 网络可用再启动相关服务

### ISSUE THREAD

**Issue by lvii** [shadowsocks/shadowsocks-libev#2105]
`rpm/SOURCES/systemd/shadowsocks-libev.service` 已配置 `network-online.target`

能够等待 **网络可用** 后再启动相关服务：

https://github.com/shadowsocks/shadowsocks-libev/blob/0a8d194426cbdfd19c7362993977614bf36f3ae0/rpm/SOURCES/systemd/shadowsocks-libev.service#L14

但 `rpm/SOURCES/systemd/shadowsocks-libev-server@.service` 没有配置 `network-online.target`

https://github.com/shadowsocks/shadowsocks-libev/blob/0a8d194426cbdfd19c7362993977614bf36f3ae0/rpm/SOURCES/systemd/shadowsocks-libev-server%40.service#L15

**服务器重启** 会导致相关 ss 服务没有起来

**Comment by madeye** [comment]
Please report to Fedora package maintainer instead.

**Comment by af-moonbow** [comment]
In fact, a server program is expected to be able to start up even an IP address is not yet configured.

Bind to 0.0.0.0 or [::] would do this.

For those who want to bind to a specific IP, it is suggested to use  IP_FREEBIND sockopt, so that bind would work on a not existing IP. Maybe ss-server could add this.

network-online.target should be used for client program, because they really need an IP to startup.

Use network-online.target would make the OS boot process slower, because it breaks parallelism.

Detailed information about this: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
