### ISSUE TITLE
obfs-local exit unexpectedly

### ISSUE THREAD

**Issue by WordlessEcho** [shadowsocks/shadowsocks-libev#2189]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
Arch Linux x86_64 (latest)

### What did you do?
`sudo ss-local -s <server_url> -p <server_port> -m chacha20-ietf-poly1305 -k <password> --plugin simple-obfs --plugin-opts "--obfs tls --obfs-host <url> -v" -l 1080 -v`

### What did you expect to see?
Successful running.

### What did you see instead?
```
 2018-10-09 18:24:17 INFO: plugin "simple-obfs" enabled
 2018-10-09 18:24:17 INFO: initializing ciphers... chacha20-ietf-poly1305
 2018-10-09 18:24:17 INFO: listening at 127.0.0.1:1080
 2018-10-09 18:24:17 INFO: running from root user
No such file or directory
 2018-10-09 18:24:17 ERROR: plugin service exit unexpectedly
 2018-10-09 18:24:17 INFO: closed gracefully
```

### What is your config in detail (with all sensitive info masked)?
I run it without config file.

**Comment by WordlessEcho** [comment]
It is strange that running obfs-local independently will not report this error. So I create this issue under the Shadowsocks-libev.

**Comment by popsUlfr** [comment]
Hi,

that command line is incorrect, it should be : 

`ss-local -s <server_url> -p <server_port> -m chacha20-ietf-poly1305 -k <password> --plugin obfs-local --plugin-opts "obfs=tls;obfs-host=<url>" -l 1080 -v`

**obfs-local** instead of simple-obfs and the parameters expressed like `obfs=tls;obfs-host=<url>`.
It will call the plugin executable but no simple-obfs exists.

Also you don't need to run it as root and you should avoid it.

**Comment by WordlessEcho** [comment]
See also: https://github.com/shadowsocks/shadowsocks-libev/issues/1071#issuecomment-272630765
