### ISSUE TITLE
Question about tcp_only mode and DNS forwarding

### ISSUE THREAD

**Issue by hybtoy** [shadowsocks/shadowsocks-libev#2205]
Hey all, 
It is not an issue, only a question. 
Is it safe to use SS in tcp_only mode without DNS forwarding? When DNS forwarding is ON with tcp_only mode, SS is not able to handshake with server.
Thanks.

**Comment by PantherJohn** [comment]
@hybtoy It’s worth noting that DNS queries typically travel over UDP although they can be transported over TCP. Since UDP is connectionless it doesn’t involve three-way handshake. I bet UDP-based DNS forwarding is much faster. So why are you still using `tcp_only` instead of a quick and dirty `tcp_and_udp` anyway?

**Comment by hybtoy** [comment]
@PantherJohn 
I tried `tcp_and_udp` mode many times and it seems not stable as `tcp_only` in my situation. 
Seems like DPI of my internet provider resets the connection when I am not tcp_and_udp mode but the connection is better on `tcp_only` mode.

**Comment by PantherJohn** [comment]
@hybtoy Have you tried `dig` on your client machine? The problem should not be related to DPI and the `tcp_and_udp` option only determines whether the server/cli will accept certain connections over TCP/UDP.

I suggest you read the official documentation and post your conf file (server/cli) and err logs here to further track issues.
