### ISSUE TITLE
openwrt 平台从3.2.1版本开始不支持 fast-open了吗？

### ISSUE THREAD

**Issue by bluehj777** [shadowsocks/shadowsocks-libev#2236]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.1-3.2.3

### What operating system are you using?
Server:Debian 9 x64  (shadowsocks-libev 3.2.1)
Client:Openwrt 18.06.1 (shadowsocks-libev 3.2.1-3.2.3)

### What did you do?
我在openwrt 18.0.6 平台（x86 and ar7xx etc）上安装shadowsocks-libev客户端，从3.2.1版本开始报告 fast-open不被平台支持 。以前用3.2.0版本都没有这些问题，现在只能在json配置文件里把fast-open true
去掉才可正常。

### What is your config in detail (with all sensitive info masked)?
{
    "server": "x.x.x.x",
    "server_port": 443,
    "password": "password",
    "method": "chacha20-ietf",
    "plugin":"obfs-local",
    "plugin_opts":"obfs=http;obfs-host=www.baidu.com;fast-open",
    "fast_open":true,
    "timeout": 60
}

**Comment by madeye** [comment]
It means fast open is not enabled during compilation.

So, make sure your building environment has valid fast open header files.

**Comment by PantherJohn** [comment]
@bluehj777 That's the problem; since you installed the release version with `FASTOPEN_CONNECT`(not sure if it really works even on the latest Linux distros) socket option enabled at compile time instead of `MSG_FASTOPEN`, TCP Fastopen would not necessarily be available on systems without support for new API impl. According to your info you should either prevent `FASTOPEN_CONNECT` impl from being compiled on a machine that supports it or compile the source code directly on your OpenWRT router.

**Comment by bluehj777** [comment]
@PantherJohn 
thanks。i got it.
