### ISSUE TITLE
This lib is not work well on centos , is there some thing wrong, thanks

### ISSUE THREAD

**Issue by 935077727** [shadowsocks/shadowsocks-libev#2246]
我之前在搬瓦工上搭的梯子，用了一年了一直没有问题。最近不能用了，流量够，换过机房，ip,加密协议，方法都试过，都不能用。是国内又出什么政策了么？ 你们的还可以用么？

The ladder I used to build on a bricklayer has been working well for a year. Recently, it has not been work well , i have enough traffic, and i have changed to the computer room, ip, encryption protocols, methods have tried, but it can not be used. Is there any domestic policy? Can you still use them?

**Comment by 935077727** [comment]
不好意思，我改正了，谢谢

**Comment by PantherJohn** [comment]
@935077727 It appears that your government has blocked almost all IP addresses owned by bandwagonhost; I've heard of it quite recently.
您的政府似乎已经阻止了bandwagonhost拥有的几乎所有IP地址。

**Comment by misudoll** [comment]
试试GCP吧，搬瓦工用的人多了就炸了。有张信用卡就行，送$300. 基本够用一年的。 https://cloud.google.com/

My ss works perfect. I think you may try another server provider, like Google Cloud Platform, they offer a free trial with $300 for a year, all you need is a valid credit card.

To me, it looks like a network carrier issue rather than a software error. A lot of service providers are doomed in mainland China, suggest you use your own server.

**Comment by 935077727** [comment]
got it,thanks all guys

**Comment by txdywy** [comment]
另外gcp可不止一年哦，去youtube上看视频，通过换账户可以无限续命🤪

Sue <notifications@github.com> 于 2018年12月17日周一 15:50写道：
