### ISSUE TITLE
Whatsapp calls only rings but not get connected[Question]

### ISSUE THREAD

**Issue by shadowmigue** [shadowsocks/shadowsocks-libev#2330]
### What version of shadowsocks-libev are you using?
v3.2.5

### What operating system are you using?
IOS and Android

### What did you do?
Just used ShadowRocket and Shadowsocks for android and when i call it just keep ringing but doesnt get connected

### What did you expect to see?
Working calls on whatsapp using shadowsocks

### What did you see instead?
No working calls using shadowsocks

### What is your config in detail (with all sensitive info masked)?

{
    "server":"0.0.0.0",
    "server_port":80,
    "local_port":1080,
    "password":"xxxx",
    "method":"chacha20",
    "timeout":1800,
    "udp_timeout":1800,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http",
    "fast_open":true,
    "reuse_port":true,
    "nofile":512000,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp"
}

**Comment by madeye** [comment]
When plug-in enabled, UDP traffic won't be forwarded. So, it's expected.

**Comment by shadowmigue** [comment]
Theres a way to traffic udp through badvpn to support calls using the plugin serverside?

**Comment by shadowmigue** [comment]
Bump, Can some one help me get udp traffic forwarded using simple obfs?

**Comment by s7lx** [comment]
@shadowmigue  
ip rule add fwmark 0x01/0x01 table 100
ip route add local default dev lo table 100
iptables -t mangle -N SSUDP
iptables -t mangle -A PREROUTING -j SSUDP
ipset -N gfwlist hash:net
iptables -t mangle -A SSUDP -p udp -m set --match-set gfwlist dst -j TPROXY --on-port $LISTEN_PORT --tproxy-mark 0x01/0x01 

@madeye  is it right ?

**Comment by shadowmigue** [comment]
Can you please help me with the iptables ports?my remort port is 80 and my local port is 1080

**Comment by edsburke** [comment]
I am trying to bump this thread since UDP relay is really needed for many apps use UDP based VoIP, e.g. Whatsapp and Facebook Messenger.  Any pull request for this feature? Thanks.

**Comment by PantherJohn** [comment]
@edsburke Perhaps we need to accept the fact that the design of the so-called shadowsocks plugin is somehow inherently broken. This is inevitably due to the fact that shadowsocks didn't adopt "modular design" in the first place. Unless you are willing to look into the code of `udprelay.c` and not bother copying a few lines of relevant code scattered across some still-actively-maintained files into it, I won't recommend using plugins at all. **But this doesn't mean you can't use the plugin entirely.** Instead you should let the plugin listen on a loopback address and specify this address as the remote address used by your shadowsocks application. That way shadowsocks should be able to forward the traffic to the plugin and let the plugin do its job instead. But if the plugin itself, which, of course, is an application as well, does not have support for relevant protocols (in your case, udp), I'm afraid this can't help you further.
