### ISSUE TITLE
feature request: tproxy mode

### ISSUE THREAD

**Issue by zh99998** [shadowsocks/shadowsocks-libev#235]
i see there is an redir mode that can transform tcp connection over shadowsocks transparently. but there is a better way called "TPROXY" to do it.
tproxy is a native tcp transparent proxy in linux, using iptables to tproxy some traffic to an local application, but without modify destination address. 

application can get destination address just using getsockname() since it's just original destination address.

tproxy is much easier and graceful than redirect. and avoiding some problem. such as packets from "lo" skip nat in iptables. i can't redirect packets from lo to shadowsocks, but tproxy works.

**Comment by madeye** [comment]
No plan for this. If you're interested, just submit a pull request.

**Comment by AttufliX** [comment]
I have encountered the same problem here. Redirect will modify the original destination IP address and won't redirect the traffic to the local port listened by shadowsocks on my linux box which doesn't act as a gateway. I don't know why until I find this issue. Thanks! I think I should use tproxy instead of redirect.
