### ISSUE TITLE
[solution found] ss-manager won't work with docker

### ISSUE THREAD

**Issue by Mirr0ch1** [shadowsocks/shadowsocks-libev#2530]
### What version of shadowsocks-libev are you using?
docker/shadowsocks/shadowsocks-libev@3.3.3

### What did you expect to see?
the function ss-manager works as normal.
instead, process ss-manager won't boot up due to lack of permission to creating new folders.
currently, ss-manager generates config files under `~/.shadowsocks`, which is not pre-built into the docker image, resulting in the situation.

### What should be done in order to make it work?
a folder named `.shadowsocks` should be pre-defined in the dockerfile.

before that, we can create a `.shadowsocks` folder outside the docker image, then have it transferred into the container using `docker cp` command to work around with this issue.

**Comment by fhwo13** [comment]
How to use ss-manager's "-D" in json configuration files
[-D <path>]                Path to the working directory of ss-manager.

**Comment by joeytwiddle** [comment]
I used `-v` to mount my external `.shadowsocks` folder into the container, but encountered the following issue:

Since `ss-manager` runs as `nobody`, I found it had trouble writing to the folder.

`chown`-ing the folder didn't seem to help (perhaps the wrong UID) so in the end I had to give everybody write permission to the `.shadowsocks` folder on my host filesystem: `chmod o+rwx .shadowsocks` Not ideal but it worked.

If there is a better way to do this, perhaps the recommended way should be added to the docs.
