### ISSUE TITLE
Support muti-port or server  for client

### ISSUE THREAD

**Issue by LazyZhu** [shadowsocks/shadowsocks-libev#260]
Large data communication with only one server:port will still be a strong feature to detect proxy by
 GFW, support muti-port or muti-server 
load balnce for client site is a good idea.
https://github.com/shadowsocks/shadowsocks/commit/783a6ef7f294b71e22b4d485545b4a7c32a651c6

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/pull/236

https://github.com/shadowsocks/shadowsocks-libev/issues/43

**Comment by LazyZhu** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/local.c#L803
Sorry, I'm didn't know that.

**Comment by LazyZhu** [comment]
May be using -s ip:port format replace -s  ip and -p port options？

**Comment by hydrandt** [comment]
Hi everyone,

I am trying to get a HA (highly available) client setup on OpenWRT, using shadowsocks-libev-spec.

I was not successful with specifying the servers in the json config like this:

<pre>
"server": ["1.1.1.1", "2.2.2.2"], 
</pre>

The only way I could start ss-redir to connect to multiple servers was:

<pre>
ss-redir -s 1.1.1.1 -s 2.2.2.2 -l 1080 -k secret.password -p 1234 -m aes-256-cfb -t 60 -b 0.0.0.0 -u -v
</pre>

How is this configuration supposed to behave?

From what I just tried, if the currently used server is 1.1.1.1 and I kill shadowsocks server there, the client immediately switches to 2.2.2.2. However, if I now start the server on 1.1.1.1 again, and kill it on 2.2.2.2, ss-redir writes "ERROR: getpeername: Transport endpoint is not connected" on stdout and stays this way. After I start the server on 2.2.2.2 again, connection is restored, and the 1.1.1.1 server is in use.

Is this the expected behavior?

It would be great to have round-robin behavior here: If the current server stops responding, connect to next one, and when the last one stops responding, start again with the first one. What do you think?

Thank you so much for your great work. Shadowsocks makes life in China possible.
