### ISSUE TITLE
Shadowsocks shadowsocksR bug whatsapp  and google playstore

### ISSUE THREAD

**Issue by serverlinuxit** [shadowsocks/shadowsocks-libev#2679]
I tried Shadowsocks and ShadowsockR and enabled UDP forwading, I use it on a smartphone but can't use whatsapp video calls and open Google Playstore

**Comment by RebelliousWhiz** [comment]
That's very much not likely to be Shadowsocks or ShadowsocksR problem.

`Ping` your server and see if it's not dropping too many packages.

Open up the necessary ports on the server to let video call packages go through.

If you are using Shadowsocks service from a third party or a service provider, ask them to help.

**Comment by serverlinuxit** [comment]
thank you for the reply. I installed on digitalocean vps and vultr and tried on smartphones and on the router activates UDP forwading but I can't video call WhatsApp. can you tell me which port I have to open so I can use whatsapp video calls and access Google Playstore. I use the install scripts from github teddysun. thanks in advance

**Comment by RebelliousWhiz** [comment]
For ports, please [google](https://www.google.com/search?newwindow=1&biw=1920&bih=933&sxsrf=ALeKk033Aj8MmT03PCTsFK1zIfuLjDoLfg%3A1586411399237&ei=h7eOXv_6DYHWmAXmm7uYCg&q=ports+for+whatsapp&oq=ports+for+whatsapp&gs_lcp=CgZwc3ktYWIQAzICCAAyAggAMgYIABAWEB4yBggAEBYQHjoECAAQRzoECCMQJzoFCAAQkQI6BQgAEIMBOgQIABBDOgcIABAUEIcCSisIFxInMGcxMDZnMTA3Zzk3ZzkwZzk0Zzg3Zzg2ZzgxZzc5Zzk1ZzkzZzEwSh0IGBIZMGcxZzFnMWcxZzFnMWcxZzFnMWc1ZzRnMVCgug9Y0NMPYKrVD2gAcAF4AIABgQGIAbIMkgEEMTQuNJgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwi_2qz_0troAhUBK6YKHebNDqMQ4dUDCAw&uact=5) it.

But I doubt opening up ports will do any help since digitalocean and vultr connection from China aren't stable, and UDP connection is very limited.

Test your connection to your server, both TCP and UDP, then try other things.

You know if it has significant packet loss, it's not going to work well anyways... In that case you might want to try some solutions like `wangyu-/UDPspeeder`.
