### ISSUE TITLE
有关自启动使用config.json的问题

### ISSUE THREAD

**Issue by UISAHF** [shadowsocks/shadowsocks-libev#445]
config.json下怎么配置udp转发呢..
我查阅了server.c源码 并未找到相关设置(当然有可能是我实在看走眼)
请问是可以在这里配置还是不可以呢
如果可以 请问一下怎么办呢
谢谢

**Comment by madeye** [comment]
Nope, you cannot enable UDP through config file.

**Comment by 70599** [comment]
启动参数加上-u

**Comment by maddie** [comment]
Actually it would be great to have to ability to enable UDP relay through config file. Now on Arch Linux, I'll have to maintain another copy of the .service file with the `-u` switch under `/etc/systemd/system` so later upgrades won't override what I've changed in the service file.

While this work for now, it's impossible to guarantee that the bundled .service file won't be changed in the future, it would be a quite a hassle to maintain the modified .service file in the long term.

**Comment by madeye** [comment]
@maddie You should modify `/etc/default/shadowsocks-libev` to add the `-u` option, not in the service scirpts.

**Comment by maddie** [comment]
@madeye Thanks for your suggestion. But it seems `/etc/default/shadowsocks-libev` is not present after install, so I didn't know it can be configured there. I assume that the content should be the same as in [this file](https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.default)? Since Arch Linux uses systemd instead, I'm not sure if this file would ever get read upon service start.

**Comment by maddie** [comment]
@madeye So it seems both `/etc/default/shadowsocks-libev` and `/usr/lib/systemd/system/shadowsocks-libev.service` is not available after installing from Arch Linux's community repo. I've added them by hand and now it works flawlessly.

Thanks for your help.

**Comment by hosiet** [comment]
@maddle
`shadowsocks-libev` in Archlinux delivers different systemd service files compared to upstream here, since they uses `libcap2` in addition to change the `capabilities` of binaries.

Check out the info in archlinux repo: https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/shadowsocks-libev
