### ISSUE TITLE
Server and clinet with One-time Auth

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/shadowsocks-libev#523]
I found that if the Clinet enable the "OTA", It will work whether the Server enable "OTA" or not .
But while the Server enable the "OTA", The Client must enable "OTA". I think it will be more safe that if the Server disable the "OTA" and the clinet should disable the "OTA" either.

**Comment by madeye** [comment]
By default, the server that supports OTA should run in the compatible mode. OTA is only applied if the client's request header has a flag set. However, if the server switch on OTA explicitly, all clients must switch on OTA, otherwise connections will be denied.

https://shadowsocks.org/en/spec/one-time-auth.html

**Comment by madeye** [comment]
It means you won't have an option to disable OTA, as it's already part of shadowsocks protocol.
