### ISSUE TITLE
How to limit the speed of the specific port?

### ISSUE THREAD

**Issue by 1558204459** [shadowsocks/shadowsocks-libev#672]
How to limit the speed of some ports?

**Comment by madeye** [comment]
https://github.com/magnific0/wondershaper

**Comment by 1558204459** [comment]
Wondershaper can only limit the whole network's speed,not some ports speed

**Comment by madeye** [comment]
https://github.com/mariusae/trickle

**Comment by 1558204459** [comment]
This tool is helpless

**Comment by xnoreq** [comment]
Why is trickle helpless? It's a userland, per-process bandwidth shaper.
If you want more control then use iptables and tc.

But this issue tracker is not the place to discuss this.

**Comment by albypeace** [comment]
@1558204459 for future reference _(since this issue is one of the top results that pop up when you google "limit bandwidth per port shadowsocks")_, I have found a series of commands using "tc" and "iptables" that allow you to obtain what you want, i.e. limit bandwidth per port. 
See here:  [https://github.com/shadowsocks/shadowsocks/issues/792](https://github.com/shadowsocks/shadowsocks/issues/792)
