### ISSUE TITLE
CentOS7 下更新到最新的 shadowsocks-libev-2.4.6-1.el7.centos.x86_64 后无法systemctl启动

### ISSUE THREAD

**Issue by whao** [shadowsocks/shadowsocks-libev#719]
今天更新了一下服务器，发现shadowsocks不能自己启动了。在centos下一直用的是systemctl的service的enable start status。检查了shadowsocks-libev.service等文件没有发现什么问题。手动通过ss-server -c config.json -u nohup & 的形式可以正常启动运行。下面是systemctl status的信息，

`● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-07-11 05:57:20 EDT; 18min ago
  Process: 644 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS (code=exited, status=216/GROUP)
 Main PID: 644 (code=exited, status=216/GROUP)

Jul 11 05:57:20 us-sfo-do-0 systemd[1]: Started Shadowsocks-libev Default Server Service.
Jul 11 05:57:20 us-sfo-do-0 systemd[1]: Starting Shadowsocks-libev Default Server Service...
Jul 11 05:57:20 us-sfo-do-0 systemd[644]: Failed at step GROUP spawning /usr/bin/ss-server: No such process
Jul 11 05:57:20 us-sfo-do-0 systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=216/GROUP
Jul 11 05:57:20 us-sfo-do-0 systemd[1]: Unit shadowsocks-libev.service entered failed state.
Jul 11 05:57:20 us-sfo-do-0 systemd[1]: shadowsocks-libev.service failed.`

根据 Jul 11 05:57:20 us-sfo-do-0 systemd[644]: Failed at step GROUP spawning /usr/bin/ss-server: No such process 后在/etc/default/shadowsocks-libev文件中发现有写明

> Note: `START', `GROUP' and `MAXFD' options are not recognized by systemd. Please change those settings in the corresponding systemd unit file.

之后删除了/usr/lib/systemd/system/shadowsocks-libev.service中service下GROUP那一行之后就可以正常启动了。不知道有没有人遇到和我同样的问题希望可以帮到你。另外就是不知道这是不是一个bug是不是打包的时候需要修复一下。

Best

**Comment by madeye** [comment]
CentOS distribution is not maintained here.

**Comment by ooogooo** [comment]
我也是遇上这个问题,还提问,搞了一天,都没有搞定,重新安装了N次
哎,早点看到你的答案就好了

**Comment by luxin88** [comment]
because there's no "nogroup" group in CentOS 7, but in debian, so just edit /usr/lib/systemd/system/shadowsocks-libev.service change Group=nogroup to Group=nobody and restart

**Comment by HashCon** [comment]
我在kali下按照https://dreamcreator108.com/dreams/debian-stretch-ssr-client/安装服务器端能启动，客户端
SSRR.service - SSRR Client Service
   Loaded: loaded (/root/.config/systemd/user/SSRR.service; enabled; vendor pres
   Active: failed (Result: exit-code) since Thu 2018-05-17 08:57:05 CST; 2min 34
  Process: 1430 ExecStart=/usr/bin/python /home/Softwares/Proxy/shadowsocksr/sha
 Main PID: 1430 (code=exited, status=2)

5月 17 08:57:05 kali2018 systemd[1410]: Started SSRR Client Service.
5月 17 08:57:05 kali2018 python[1430]: /usr/bin/python: can't open file '/home/S
5月 17 08:57:05 kali2018 systemd[1410]: SSRR.service: Main process exited, code=
5月 17 08:57:05 kali2018 systemd[1410]: SSRR.service: Failed with result 'exit-c
不知如何解决，希望大神能帮忙。

**Comment by fjalimama** [comment]
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 四 2019-09-05 18:05:59 CST; 3min 39s ago
     Docs: man:shadowsocks-libev(8)
 Main PID: 16662 (code=exited, status=255)

9月 05 18:05:59 localhost.localdomain systemd[1]: Started Shadowsocks-libev Default Server Service.
9月 05 18:05:59 localhost.localdomain systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=255/n/a
9月 05 18:05:59 localhost.localdomain systemd[1]: Unit shadowsocks-libev.service entered failed state.
9月 05 18:05:59 localhost.localdomain systemd[1]: shadowsocks-libev.service failed.
 [root@localhost /etc/yum.repos.d 18:09:38 4.2  ]# nano /etc/shadowsocks-libev/config.json
 [root@localhost /etc/yum.repos.d 18:10:22 4.2  ]# ss-server -c config.json
 2019-09-05 18:13:34 ERROR: Invalid config path.
