### ISSUE TITLE
how to build shadowsocks-libev on macOS with libcrypto/libpcre as static library

### ISSUE THREAD

**Issue by humiaozuzu** [shadowsocks/shadowsocks-libev#843]
As we need to deploy it on many Macs of out workmates, while most of their computers do not have Xcode and Homebrew installed.

I've build successfully on mac but do not know how to build libcrypto/libpcre as static library. My process

```bash
export OBJC=clang
export CC=clang
export OBJCXX=clang++
export CXX=clang++
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig
export PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
./configure --prefix=/Users/maple/Downloads/ss-libev --with-openssl=/usr/local/opt/openssl --with-pcre=/usr/local/opt/pcre
make
```

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/821#issuecomment-246153870

**Comment by qinyuhang** [comment]
@humiaozuzu hi did you fix this problem? I am in a exactly situation with you, I have try compile ss-local for my workmates, will they run it ss-local crash with these logs: 

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/USER/Library/Application Support/ShadowsocksX-NG/ss-local
  Reason: image not found
```
(and I know it is because they did not try `brew install pcre` so it means in their Mac there is no libpcre and I want try link libcrypto and libpcre direct into ss-local )
