### ISSUE TITLE
help! can not start the shadowsocks-libev services

### ISSUE THREAD

**Issue by baizi2k** [shadowsocks/shadowsocks-libev#859]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

2.3.3
### What operating system are you using?
Debian 7.0

### What did you do?
root@yacss:~# sudo /etc/init.d/shadowsocks-libev start

shadowsocks-libev 2.3.3

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:

    ss-[local|redir|server|tunnel|manager]

       -s <server_host>           host name or ip address of your remote server

### What did you expect to see?

shadowserivers startup
### What did you see instead?
 print some werid usage

### What is your config in detail (with all sensitive info masked)?

root@yacss:~# sudo vim /etc/shadowsocks-libev/config.json
{
    "server":"168.235.54.227",
    "port_passwod":{
        "5900":"yeah888",
        "5901":"finalzzn"
        },
    "timeout":5000,
    "method":"rc4-md5",
        "fast_open":false,
        "workers":1
}

**Comment by hosiet** [comment]
Unlike the Python version, ss-server won't work with port_password. Please use "password" instead.

If you need to spawn multiple instances, you need to use ss-manager or custom management scripts since you are not using systemd (Debian 7.0). Sysvinit service could only provide single instance of ss-server.

Also please try to compile and use the latest version (2.5.3), 2.3.3 is outdated.

**Comment by baizi2k** [comment]
@hosiet That's help.Thk u very much.
