### ISSUE TITLE
A questions for -b <local_address> in ss-server

### ISSUE THREAD

**Issue by ss-plus** [shadowsocks/shadowsocks-libev#943]
I wonder the usage of -b  -b <local_address> in server mode.
what difference with the argument server?

**Comment by madeye** [comment]
-i <interface>
Send traffic through specific network interface.

For example, there are three interfaces in your device, which is lo (127.0.0.1), eth0 (192.168.0.1) and eth1 (192.168.0.2). Meanwhile, you configure ss-local to listen on 0.0.0.0:8388 and bind to eth1. That results the traffic go out through eth1, but not lo nor eth0. This option is useful to control traffic in multi-interface environment.

-b <local_address>
Specify local address to bind. It works like -i <interface> but binds to address instead of interface.

**Comment by ss-plus** [comment]
I wanna the usage in server mode not local and redir mode.
I found the argument "-b <local_address>" was not available in server mode with the argument “-s 0.0.0.0”.
